kind: pipeline
type: docker
name: sleep

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - sleep 30
  - echo world

---
kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world


---
kind: pipeline
type: docker
name: npm

steps:
- name: npm_install
  image: alpine
  commands:
  - npm install
  - echo 'install finish'
